doctrine:
  dbal:
    url: '%env(resolve:DATABASE_URL)%'
    driver_class: PHP_SF\System\Database\DoctrineEntityManager
  orm:
    auto_generate_proxy_classes: false
    naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
    auto_mapping: true
    proxy_namespace: Proxies
    mappings:
      App:
        is_bundle: false
        type: attribute
        dir: '%kernel.project_dir%/App/Entity'
        prefix: 'App\Entity'
        alias: App