version: '3.1'
services:
    memcached:
        image: 'memcached:alpine'
        ports:
            -   '7001:11211'

    redis:
        image: 'redis:alpine'
        ports:
            -   '7002:6379'

    postgres:
        image: 'postgres:15-alpine'
        working_dir: /application
        volumes:
            - '.:/application'
        environment:
            - POSTGRES_USER=root
            - POSTGRES_PASSWORD=bP43!46@v14uuCQDMY1r
            - POSTGRES_DB=php-sf-docs
        ports:
            - '7005:5432'

    webserver:
        image: 'nginx:alpine'
        working_dir: /application
        volumes:
            - '.:/application'
            - './phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf'
        ports:
            - '7000:80'

    php-fpm:
        build: phpdocker/php-fpm
        working_dir: /application
        volumes:
            - '.:/application'
            - './phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/8.2/fpm/conf.d/99-overrides.ini'
