# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:

services:
  # default configuration for services in *this* file
  _defaults:
    autowire: true      # Automatically injects dependencies in your services.
    autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

  Doctrine\Bundle\FixturesBundle\Loader\SymfonyFixturesLoader:
    alias: 'doctrine.fixtures.loader'

  Symfony\Component\Form\FormFactory:
    public: true

  app.cache.adapter.redis:
    parent: 'cache.adapter.redis'
    tags:
      - { name: 'cache.pool', namespace: '%env(resolve:SERVER_PREFIX)%' }

  # make classes in App/ available to be used as services
  # this creates a service per class whose id is the fully-qualified class name
  App\:
    resource: '../App/'
    exclude:
      - '../App/Http/'
      - '../App/DoctrineLifecycleCallbacks/'
      - '../App/DependencyInjection/'
      - '../App/Entity/'
      - '../App/Router.php'
      - '../App/Kernel.php'
      - '../App/Tests/'
      - '../App/DataFixtures/Purgers/'
      - '../App/Helpers/'
      - '../App/EventListeners/'
      - '../App/Enums/'
      - '../tests/'

  # add more service definitions when explicit configuration is needed
  # please note that last definitions always *replace* previous ones
